version: "3.8"
services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      APP_NAME: ${APP_NAME}
      BCRYPT_SALT: ${BCRYPT_SALT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      REDIS_URL: ${REDIS_URL}
      REDIS_EXPIRES_IN: ${REDIS_EXPIRES_IN}
    ports:
      - 4000:4000
    depends_on:
      - database
      - redis